# Generated by Django 4.0.6 on 2022-08-13 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Şirkət Adı')),
            ],
            options={
                'verbose_name': 'Şirkət',
                'verbose_name_plural': 'Şirkətlər',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Dərman Adı')),
                ('expirate', models.DateField()),
                ('price', models.IntegerField()),
                ('recipe_needed', models.BooleanField()),
                ('factory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.factory')),
            ],
            options={
                'verbose_name': 'Dərman',
                'verbose_name_plural': ['Dərmanlar'],
            },
        ),
    ]
